changes to participant. Closes #416
International-Data-Spaces-Association/InformationModel pull request #423
Opened 2021-03-25 10:44 UTC by HaydarAk

2021-03-29 08:53 UTC, JohannesLipp requested changes
Minor changes, please revise these. Thanks!

2021-03-29 08:53 UTC, JohannesLipp commented on model/participant/Participant.ttl
> +ids:vatID
Please be consistent with the property naming. Either add "hasProperty" or "property" to all (cf. `hasBusinessIdentifier` vs `vatID`), thanks!

2021-03-29 08:53 UTC, JohannesLipp commented on model/participant/Participant.ttl
> +ids:vatID
Also see `legalForm` and `jurisdiction` below.

2021-03-29 08:53 UTC, JohannesLipp commented on model/participant/Participant.ttl
> +ids:jurisdication
IMHO, the proper spelling is `jurisdiction` - please double-check and also update label and comment if required, thanks!

2021-03-29 08:53 UTC, JohannesLipp commented on testing/participant/ParticipantShape.ttl
> +		#sh:minCount 1 ;
We should either remove this commented-out line, or add a proper comment to explain possible future development. Please also see the two following properties below.

2021-04-08 11:48 UTC, HaydarAk commented
Alle suggestions should be resolved via 03969e0.
Could you re-check :) ?

2021-04-08 13:14 UTC, JohannesLipp approved these changes
Thank you for addressing all requested changes. Good work.

2021-04-12 07:24 UTC, merged