Documentation Application Profiles and Workflow for Domain-specific Extensions
International-Data-Spaces-Association/InformationModel pull request #543
Opened 2022-02-23 13:46 UTC by JohannesLipp

Part of the results of T60, refers to #504  #540 and others

2022-03-08 10:14 UTC, liam-tirpitz requested changes

2022-03-08 10:37 UTC, JohannesLipp commented
> Both pdf files contain comments and questions in red. Please check, if the files should contain these comments before merging.

Good point!

@lcomet please update both PDF files for clarity, thanks! That is:

- Replace the single comment in the ExtendSHACLshapes with "No changes"
- Remove/replace all comments in the other PDF file, as we dropped or implemented all these anyway.

2022-03-08 10:50 UTC, JohannesLipp commented on evaluation_external/README.md
> +Another possibility is to use the existent definitions in the **IDS Information model** and we want to tighten the restrictions, for example for the properties `dcat:mediaType`, `ids:representationSt
```suggestion
Another possibility is to take existing definitions from the **IDS Information model** and tighten their restrictions, for example for the properties `dcat:mediaType`, `ids:representationStandard `, and `ids:instsance`.
```

2022-03-09 14:11 UTC, liam-tirpitz requested changes

2022-03-09 14:21 UTC, liam-tirpitz requested changes
The ,DS-Store file should not be committed to the repository. Please delete it.

2022-03-09 14:34 UTC, liam-tirpitz approved these changes

2022-03-09 14:36 UTC, JohannesLipp commented
> The ,DS-Store file should not be committed to the repository. Please delete it.

done, thanks for the hint!

2022-03-17 13:27 UTC, merged