Add LogEntry + Shape
International-Data-Spaces-Association/InformationModel pull request #575
Opened 2022-06-30 13:27 UTC by PHochmann

2022-06-30 13:52 UTC, kragall commented
Hi, so I checked with the current version of the Clearing House and saw that the originally requested structure doesn't fit anymore. So I wondered if it's possible to adjust the changes to fit this structure:

- **timestamp**: This is the timestamp recording the date when this message was logged by the CH
- **transaction_id**: This is basically a counter with a unique (unique in the database) number for each stored message.
- **process_id**: This is a string that describes the process under which the message is logged. Think of it as the label of the folder under which the message has been filed together with other messages.
- **document_id**: This is a unique (unique in the process) id in the form of a uuid for the stored message
- **client_id**: This is the unique id of the client that sent the stored message taken from the DAT the client sent with the original LogMessage
- **server_id**: This is the unique id of the server that stored message in form of the id of private key
- **hash**: This information is used for integrity protection in the CH
- **signature**: This contains a cryptographic signature of the data
- **payload**: This optional field contains the payload of the original LogMessage

Please note that in the original request LogEntry contained a LogMessage. This is not the case anymore.

2022-07-01 08:14 UTC, PHochmann commented
> Hi, so I checked with the current version of the Clearing House and saw that the originally requested structure doesn't fit anymore. So I wondered if it's possible to adjust the changes to fit this structure:
>     * **payload**: This optional field contains the payload of the original LogMessage

Is this payload a string or another Data Type property, or does it point to another object? I can't find any information about what a LogMessage's payload looks like.

2022-07-11 13:17 UTC, kragall commented
The payload does not reference another entity, so it's probably best to use a string

2022-07-13 08:33 UTC, PHochmann commented
Edits are under taxonomies/Message.ttl @kragall Please have a look

2022-07-18 13:18 UTC, kragall requested changes

2022-08-01 10:09 UTC, JohannesLipp requested changes

2022-08-01 10:09 UTC, JohannesLipp commented on taxonomies/Message.ttl
> +    rdfs:comment "Links a LogEntry (Metadata) to a transactionID"@en .
@PHochmann I suggest to add `rdfs:label` to all newly added properties. That would basically be readable versions of their URIs, like `transactionID` -> `transaction id/ID`

2022-08-01 10:09 UTC, JohannesLipp commented on taxonomies/Message.ttl
> +ids:hasHash a owl:DatatypeProperty ;
Be more consistent with naming conventions? The other new properties do not have a verb notation (clientID, payload, signature, ...), but this one has (**has**Hash). Easy solution = remove the "has" part from this line?

```suggestion
ids:hash a owl:DatatypeProperty ;
```

2022-08-01 10:46 UTC, kragall commented on taxonomies/Message.ttl
> +    rdfs:label "Log Entry"@en ;
389 and 390 are the same. Is that a c&p error?

2022-08-10 10:13 UTC, PHochmann commented
All requested changes are now resolved, feel free to review and merge. Thanks!

2022-08-11 06:02 UTC, JohannesLipp approved these changes

2022-08-11 07:25 UTC, merged